repo_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
cd(repo_root);
addpath(genpath(fullfile(repo_root, 'src')));
addpath(genpath(fullfile(repo_root, 'scripts', 'current')));

prefix = fullfile(repo_root, 'results', 'raw', 'beta_2p2_4', 'Gphase30x_betalin2p2to4_h3');

run_phase_diagram( ...
    prefix, ...
    100, ...
    0.3, ...
    5, ...
    0.0, 4.5, 0.15, ...
    500, ...
    500, ...
    3, ...
    2.2, 4.0, 0.2, ...      % beta grid
    100000, ...
    10000, ...
    'heaviside3', ...
    1 ...
);
